# Generated by Django 5.2.8 on 2025-12-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('previous_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем работал')),
                ('desired_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем хочет работать')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('social_network', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соц сеть')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('language', models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
    ]
